#!/usr/bin/env python

import sys
import logging
import tool.args_parser
import tool.util
import connect.connection
import client.iters


#Parse arguments
args = tool.args_parser.docker_migrate_client_parse()

#logging configuration
logging.basicConfig(filename=args.log_file, filemode="a", level=logging.INFO,
                    format="%(asctime)s.%(msecs)03d: %(process)d: %(message)s",
                    datefmt="%H:%M:%S")

# Setup hook to log uncaught exceptions
sys.excepthook = tool.util.log_uncaught_exception
tool.util.log_header()
logging.info("Starting migrate!")

#Establish connection
connection = connect.connection.establish(args.fdmem,args.fdrpc,args.fdfs)

#Start migration
controller = client.iters.migration_iter_controller(args.ct_id,args.to,connection,args.mode,args.fs_driver)
controller.set_options(vars(args))
controller.start_live_migration()

#Close Connection
connection.close()
